server:
  port: 9001
spring:
  application:
    name: app-eureka

eureka:
  instance:
    hostname: localhost
  client:
    # 是否向服务注册中心注册自己，默认是true
    register-with-eureka: false
    # 是否检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.92.128:9000/eureka/
