server:
  port: 8001

spring:
  application:
    name: app-gateway
  profiles:
    active: dev
  cloud:
    config:
      enabled: true
      profile: dev
      name: ${spring.application.name}-${spring.profiles.active}
      discovery:
        service-id: app-config

  config:
    import: optional:configserver:http://APP-CONFIG

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://192.168.92.128:9000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  routes:
    user-basic:
      service-id: user-basic
      path: /user-basic/**
